[package]
name = "frames-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-cors = "0.7.0"
juniper = "0.16.1"
env_logger = "0.11.5"
log = "0.4.22"
sqlx = { version = "0.8" , features = ["runtime-async-std", "tls-native-tls" , "sqlite"] }
