[package]
name = "ble_decode"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.128"
aes = "0.8"
ccm = "0.5"
